@baseUrl = http://localhost:2700
@userId = 7d0a2367-2cb0-45c6-9711-c2026e32a243
@Token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiI3ZDBhMjM2Ny0yY2IwLTQ1YzYtOTcxMS1jMjAyNmUzMmEyNDMiLCJlbWFpbCI6ImNhcmxpdG9zMjMzQHRoaXNpc3ZhbmsuY29tIiwibmFtZSI6IkFyYmV5IE9yb3pjbyIsImlhdCI6MTczOTI0NTU0MywiZXhwIjoxNzM5MjQ5MTQzfQ.3p_FZYX6zRD1Bv-1u8QJScoeCFHSYGzC5CCJDpgpnJA
@ResetToken=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VySWQiOiIyNjE2NjQxZi02NDU5LTRhYTAtYTZlYS0yY2IwYWIxYmI5MjQiLCJpYXQiOjE3Mjg3MDYzMzcsImV4cCI6MTcyODcwNzIzN30.OhL74P5ux9SAyUfO6oxfZq-oOygltOEUIU61z6EKiwY
@productId=fed76de8-917d-42d3-98a9-45f956238337

### Crear un nuevo usuario Admin
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "name": "Admin",
    "email": "admin2@example.com",
    "password": "Arbey2321",
    "role": "admin"
}

### Crear un nuevo usuario
POST {{baseUrl}}/api/users
Content-Type: application/json

{
    "name": "Arbey Orozco",
    "email": "carlitos233@thisisvank.com",
    "password": "123456"
}

### Autenticar un usuario Administrator
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "carlitos233@thisisvank.com",
    "password": "123456"
}

### Autenticar un usuario
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
    "email": "SantiagoMurielOrozco@gmail.com",
    "password": "SantiagoMuriel29"
}

### Obtener todos los usuarios (solo admin)
GET {{baseUrl}}/api/users
Authorization: Bearer {{Token}}

### Obtener un usuario por ID
GET {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{Token}}

### Actualizar un usuario por ID (solo admin)
PUT {{baseUrl}}/api/users/{{userId}}
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "name": "SantiagoMuriel29",
    "email": "SantiagoMurielOrozco29@gmail.com",
    "password": "SantiagoMuriel29"
}

### Eliminar un usuario por ID (solo admin)
DELETE {{baseUrl}}/api/users/{{userId}}
Authorization: Bearer {{Token}}

### Actualizar perfil
PUT {{baseUrl}}/api/users/{{userId}}/profile
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "name": "Santiago Muriel Orozco",
    "email": "Santiago29@gmail.com"
}

### Solicitar token de reseteo de contraseña
POST {{baseUrl}}/api/auth/request-reset-password
Content-Type: application/json

{
    "email": "admin@example.com"
}

### Cambiar contraseña usando token
PUT {{baseUrl}}/api/auth/reset-password
Content-Type: application/json

{
    "token": "{{ResetToken}}",
    "newPassword": "Semeolvido"
}


### Agregar producto a favoritos (requiere autenticación)
POST {{baseUrl}}/api/products/favorites
Content-Type: application/json
Authorization: Bearer {{Token}}

{
    "name": "iPhone",
    "price": 999.99,
    "url": "https://example.com/iphone14.jpg", 
    "image_url": "https://example.com/iphone14.jpg"

}

### Obtener productos favoritos del usuario (requiere autenticación)
GET {{baseUrl}}/api/products/Getfavorites
Authorization: Bearer {{Token}}

### Eliminar producto de favoritos (requiere autenticación)
DELETE {{baseUrl}}/api/products/favorites/{{productId}}
Content-Type: application/json
Authorization: Bearer {{Token}}
